# @package _global_

defaults: # Importe
  - anysleep_config@_global_
  - ../sweeper/basic_sweep_config@_global_
  - ../usleep_split.yaml@datasets
  - _self_

data:
  train_dataloader:
    dataset:
      batch_size: 32
